name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
        # Check for the latest version at 
        # https://dotnet.microsoft.com/download/dotnet/5.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
